---
  version: "2"

  services:

    dansguiden:
      build: .
      container_name: dansguiden
      environment:
        NODE_MEMORY_LIMIT: 200
        NODE_PORT: 3000
        NODE_DEBUG: "app:*"
      ports:
        - "3000:3000"
      volumes:
        - "./storage:/app/storage"
