---
  version: "2"

  services:

    dansguiden:
      build: .
      container_name: dansguiden
      environment:
        NODE_MEMORY_LIMIT: 512
        NODE_PORT: 5000
        DEBUG: "app:*"
      ports:
        - "5000:5000"
      volumes:
        - "./storage:/app/storage"
